@startuml classes
set namespaceSeparator none
class "Database" as database.db.Database #aliceblue {
  connection
  cursor
  INVENTORY
  database_path : str
  insert_new_vehicle(self, vin: int, make: str, model: str, mileage: int, price: int, image_url: str,body_style: str) -> None
  get_full_inventory(self):
  get_all_vehicle_vin(self):
  get_vehicle_make_by_vin(self, vin: int)
  get_vehicle_model_by_vin(self, vin: int)
  get_vehicle_price_by_vin(self, vin: int)
  get_vehicle_mileage_by_vin(self, vin: int)
  get_vehicle_image_url_by_vin(self, vin: int)
  get_vehicle_body_style_by_vin(self, vin: int)
  set_vehicle_make(self, vin: int, new_make: str)
  set_vehicle_model(self, vin: int, new_model: str)
  set_vehicle_price(self, vin: int, new_price: float) 
  set_vehicle_mileage(self, vin: int, new_mileage: int)
  set_vehicle_image_url(self, vin: int, new_image_url: str)
  set_vehicle_body_style(self, vin: int, new_body_style: str)
  USERS
  insert_user(self, username: str, password_hash: str, email: str, first_name: str, last_name: str) -> None
  get_all_user_information(self)
  get_password_hash_by_username(self, username: str)
  get_email_by_username(self, username: str)
  get_first_name_by_username(self, username: str)
  get_last_name_by_username(self, username: str)
  get_permission(self, username: str)
  set_password_hash(self, username: str, new_password_hash: str)
  set_email(self, username: str, new_email: str)
  set_first_name(self, username: str, new_first_name: str)
  set_last_name(self, username: str, new_last_name: str)
  set_permission(self, username: str)
  SALES
  insert_new_sale(self, transaction_id: int, username: str, item_id: int, quantity: int, sale_date: dt.date, cost: float)
  get_full_sales_information(self)
  get_transaction_id_by_sale_id(self, sale_id: int)
  get_username_by_sale_id(self, sale_id: int)
  get_item_id_by_sale_id(self, sale_id: int)
  get_quantity_by_sale_id(self, sale_id: int)
  get_sale_date_by_sale_id(self, sale_id: int)
  get_cost_by_sale_id(self, sale_id: int)
  get_full_sale_by_id(self, sale_id: int)
  get_sales_by_transaction_id(self, transaction_id: int)
  get_sales_by_username(self, username: str)
  get_sales_by_item_id(self, item_id: int)
  get_sales_by_date_range(self, start_date: dt.date, end_date: dt.date)
  get_sales_by_quantity_range(self, start_quantity: int, end_quantity: int)
  get_sales_by_cost_range(self, start_cost: float, end_cost: float)
  set_sale_transaction_id(self, sale_id: int, new_transaction_id: int)
  set_sale_username(self, sale_id: int, new_username: str)
  set_sale_item_id(self, sale_id: int, new_item_id: int)
  set_sale_date(self, sale_id: int, new_sale_date: dt.date)
  set_sale_quantity(self, sale_id: int, new_quantity: int)
  set_sale_cost(self, sale_id: int, discount: float = 0, tax: float = 0.05)
}
@enduml
