@startuml customer
left to right direction
actor Customer
rectangle "System" as system {
  (Login)
  (View inventory)
  (Remove vehicle)
  (Add vehicle)
  (Edit vehicle specs)
  (View purchases)
  (View customers)
  (Logout)
}
Customer --> (Login)
Customer --> (View inventory)
Customer --> (Remove vehicle)
Customer --> (Add vehicle)
Customer --> (Edit vehicle specs)
Customer --> (View purchases)
Customer --> (View customers)
Customer --> (Logout)
@enduml